terraform {
  required_version = ">=1.7.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
    cloudinit = {
      source  = "hashicorp/cloudinit"
      version = "2.2.0"
    }
    sops = {
      source  = "carlpett/sops"
      version = "0.7.1"
    }
    datadog = {
      source  = "datadog/datadog"
      version = "~> 3.24"
    }
  }
}
provider "cloudinit" {}
provider "sops" {}
provider "datadog" {
  validate = false
}
provider "aws" {
  region = var.aws_region
  default_tags {
    tags = {
      project   = "e2e-handshakes-liftandshift"
      env       = "e2e"
      service   = "atlantis"
      owner     = "devops"
      managedBy = "terraform"
    }
  }
}

data "aws_vpc" "default" {
  default = true
}
data "aws_subnets" "default" {
  filter {
    name   = "vpc-id"
    values = [data.aws_vpc.default.id]
  }
}

data "sops_file" "policies_conftest_secrets" {
  source_file = "../test-secrets/policies-conftest-deploy-key.enc.json"
}

data "sops_file" "atlantis_env_secrets" {
  source_file = "../test-secrets/atlantis-env.enc.json"
}

data "sops_file" "datadog_agent_secrets" {
  source_file = "../test-secrets/datadog-agent-secrets.enc.json"
}

# could be auto generated by fogg ...
module "atlantis" {
  source                          = "../../../../terraform/modules/atlantis"
  acme_email                      = local.acme_email
  ami_id                          = local.ami_id
  atlantis_server_config          = local.atlantis_server_config
  datadog_agent_config_checks_uri = local.datadog_agent_config_checks_uri
  datadog_api_key_arn             = local.datadog_api_key_arn
  datadog_host_tags               = local.datadog_host_tags
  dns_domain                      = local.dns_domain
  github_org                      = local.github_org
  hostname_atlantis               = local.hostname_atlantis
  name_prefix                     = local.name_prefix
  policies_branch                 = local.policies_branch
  policies_repo                   = local.policies_repo
  repos_yaml                      = local.repos_yaml
  subnet_id                       = local.subnet_id
  vpc_id                          = local.vpc_id
  additional_inline_policies      = local.additional_inline_policies
  tfmigrate_enabled               = local.tfmigrate_enabled
  imdsv2_enabled                  = local.imdsv2_enabled
  data_volume_type                = local.data_volume_type
  data_volume_prevent_destroy     = local.data_volume_prevent_destroy
  turbo_enabled                   = local.turbo_enabled

  providers = {
    aws         = aws
    aws.route53 = aws
  }
}

variable "ami_id" {
  type = string
}

variable "name_prefix" {
  type = string
}

variable "hostname_atlantis" {
  type    = string
  default = ""
}


variable "aws_region" {
  type    = string
  default = "ap-southeast-1"
}

variable "dns_domain" {
  type    = string
  default = "devops.handshakes.com.sg"
}

# Secrets hardcoded in AMI/module (only conftest-deploy-key needed for tests):
# - ${local.name_prefix}/atlantis/secrets
# - ${local.name_prefix}/atlantis-gh-app-key/contents
# - ${local.name_prefix}/policies-conftest-deploy-key/contents
resource "aws_ssm_parameter" "atlantis_env" {
  name        = "/${local.name_prefix}/atlantis-env/contents"
  description = "${local.name_prefix} atlantis env"
  type        = "SecureString"
  tier        = "Standard"
  value       = data.sops_file.atlantis_env_secrets.data.contents
}
resource "aws_ssm_parameter" "atlantis_secrets" {
  name        = "/${local.name_prefix}/atlantis/secrets/fake"
  description = "${local.name_prefix} Atlantis fake secret"
  type        = "SecureString"
  tier        = "Standard"
  value       = "FAKE"
}

resource "aws_ssm_parameter" "atlantis_gh_app_key" {
  name        = "/${local.name_prefix}/atlantis-gh-app-key/contents"
  description = "${local.name_prefix} Atlantis gh-app-key"
  type        = "SecureString"
  tier        = "Standard"
  value       = "FAKE"
}

resource "aws_ssm_parameter" "policies_conftest_deploy_key" {
  name        = "/${local.name_prefix}/policies-conftest-deploy-key/contents"
  description = "${local.name_prefix} git-sync deploy-key for conftest policies"
  type        = "SecureString"
  tier        = "Standard"
  value       = data.sops_file.policies_conftest_secrets.data.deployKey
}

resource "aws_secretsmanager_secret" "datadog_agent_api_key" {
  name        = "${local.name_prefix}-datadog-api-key"
  description = "Encrypted Datadog API Key"
}

resource "aws_secretsmanager_secret_version" "datadog_agent_api_key" {
  secret_id     = aws_secretsmanager_secret.datadog_agent_api_key.id
  secret_string = data.sops_file.datadog_agent_secrets.data["agent-api-key"]
}

locals {
  # under test
  ami_id            = var.ami_id
  name_prefix       = var.name_prefix
  hostname_atlantis = length(var.hostname_atlantis) == 0 ? "atlantis-${var.name_prefix}" : var.hostname_atlantis
  dns_domain        = var.dns_domain
  # static
  acme_email                  = "devops@handskakesapp.com.sg"
  acme_staging                = true
  vpc_id                      = data.aws_vpc.default.id
  subnet_id                   = data.aws_subnets.default.ids[0]
  repos_yaml                  = file("config/repos.yaml")
  github_org                  = "HandshakesByDC"
  policies_repo               = "terraform.handshakes.liftandshift"
  policies_branch             = "master"
  tfmigrate_enabled           = true
  imdsv2_enabled              = true
  data_volume_type            = "gp3"
  data_volume_prevent_destroy = false
  turbo_enabled               = true

  datadog_api_key_arn = aws_secretsmanager_secret_version.datadog_agent_api_key.arn
  datadog_host_tags   = "env:e2e-tests,service:atlantis"
  # s3 uri to sync down to /etc/confd/*
  datadog_agent_config_checks_uri = "s3://${aws_s3_bucket.datadog_agent_config.id}/datadog-checks/"

  atlantis_server_config = {
    gh-user         = "fake"
    gh-token        = "fake"
    gh-app-key-file = ""
  }

  additional_inline_policies = {
    datadog-agent = {
      policy = {
        GetApiKey = {
          actions = [
            "secretsmanager:GetSecretValue",
          ]
          resources = [
            aws_secretsmanager_secret_version.datadog_agent_api_key.arn
          ]
        }
      }
    }
    datadog-config = {
      policy = {
        S3Sync = {
          actions = [
            "s3:DeleteObject",
            "s3:GetBucketLocation",
            "s3:GetObject",
            "s3:ListBucket",
            "s3:PutObject",
          ]
          resources = [
            aws_s3_bucket.datadog_agent_config.arn,
            "${aws_s3_bucket.datadog_agent_config.arn}/*"
          ]
        }
      }
    }
    datadog-checks-data = {
      policy = {
        AllowFetchChecksConfig = {
          actions = [
            "ssm:GetParameters",
            "ssm:GetParametersByPath",
          ]
          effect    = "Allow"
          resources = [for k, v in aws_ssm_parameter.datadog_checks_contents : v.arn]
        }
      }
    }
  }
}

# module "atlantis" outputs
output "asg_name" {
  value     = module.atlantis.asg_name
  sensitive = false
}
output "role_arn" {
  value     = module.atlantis.role_arn
  sensitive = false
}
